# Generated by Django 2.2.24 on 2021-09-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adversaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='avocatadversaire',
            table='avocat_adversaire',
        ),
    ]
