# Generated by Django 2.2.24 on 2021-09-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adversaires', '0002_auto_20210930_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avocatadversaire',
            options={'ordering': ['-id'], 'verbose_name': 'AvocatAdversaire', 'verbose_name_plural': 'AvocatAdversaires'},
        ),
    ]
