# Generated by Django 2.2.24 on 2021-10-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='observation',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
