# Generated by Django 2.2.24 on 2021-09-30 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avocat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, null=True)),
                ('immeuble', models.CharField(blank=True, max_length=255, null=True)),
                ('quartier', models.CharField(blank=True, max_length=255, null=True)),
                ('indication', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, choices=[('all', 'Toutes'), ('Agadir', 'AGADIR'), ('Ahfir', 'AHFIR'), ('Ain-aouda', 'AIN\xa0AOUDA'), ('Al-aaroui', 'AL\xa0AAROUI'), ('Al-hoceima', 'AL\xa0HOCEIMA'), ('Asilah', 'ASILAH'), ('Assa', 'ASSA'), ('Azilal', 'AZILAL'), ('Azrou', 'AZROU'), ('Ben-ahmed', 'BEN\xa0AHMED'), ('Ben-slimane', 'BEN\xa0SLIMANE'), ('Bengrir', 'BENGRIR'), ('Beni-mellal', 'BENI\xa0MELLAL'), ('Berkane', 'BERKANE'), ('Berrechid', 'BERRECHID'), ('Biougra', 'BIOUGRA'), ('Bouarfa', 'BOUARFA'), ('Bouizakaren', 'BOUIZAKAREN'), ('Boujaad', 'BOUJAAD'), ('Boujdour', 'BOUJDOUR'), ('Boujniba', 'BOUJNIBA'), ('Bouznika', 'BOUZNIKA'), ('Casablanca', 'CASABLANCA'), ('Chefchaouen', 'CHEFCHAOUEN'), ('Chichaoua', 'CHICHAOUA'), ('Dakhla', 'DAKHLA'), ('Demnate', 'DEMNATE'), ('El-aioun', 'EL\xa0AIOUN'), ('El-brouj', 'EL\xa0BROUJ'), ('El-gara', 'EL\xa0GARA'), ('El-hajeb', 'EL\xa0HAJEB'), ('El-haouz', 'EL\xa0HAOUZ'), ('El-jadida', 'EL\xa0JADIDA'), ('El-karia', 'EL\xa0KARIA'), ('Erfoud', 'ERFOUD'), ('Errachidia', 'ERRACHIDIA'), ('Es-semara', 'ES-SEMARA'), ('Essaouira', 'ESSAOUIRA'), ('Fes', 'FES'), ('Figuig', 'FIGUIG'), ('Fnideq', 'FNIDEQ'), ('Fquih-ben-salah', 'FQUIH\xa0BEN\xa0SALAH'), ('Goulmima', 'GOULMIMA'), ('Guelmim', 'GUELMIM'), ('Guercif', 'GUERCIF'), ('Had-soualem', 'HAD\xa0SOUALEM'), ('Hattane', 'HATTANE'), ('Ifrane', 'IFRANE'), ('Imzouren', 'IMZOUREN'), ('Inezgane', 'INEZGANE'), ('Jerrada', 'JERRADA'), ('Kalaa-des-sraghnas', 'KALAA\xa0DES\xa0SRAGHNAS'), ('Kenitra', 'KENITRA'), ('Khenifra', 'KHENIFRA'), ('Khmisset', 'KHMISSET'), ('Khouribga', 'KHOURIBGA'), ('Ksar-el-kebir', 'KSAR\xa0EL\xa0KEBIR'), ('Ksar-sghir', 'KSAR\xa0SGHIR'), ('Ksbat-tadla', 'KSBAT\xa0TADLA'), ('Laayoune', 'LAAYOUNE'), ('Lahraouyine', 'LAHRAOUYINE'), ('Larache', 'LARACHE'), ('Mdiaq', 'MDIAQ'), ('Machraa-belksiri', 'MACHRAA\xa0BELKSIRI'), ('Marrakech', 'MARRAKECH'), ('Martil', 'MARTIL'), ('Mediouna', 'MEDIOUNA'), ('Meknes', 'MEKNES'), ('Midelt', 'MIDELT'), ('Mirleft', 'MIRLEFT'), ('Missour', 'MISSOUR'), ('Mohammedia', 'MOHAMMEDIA'), ('Mrirt', 'MRIRT'), ('Nador', 'NADOR'), ('Ouaouizerth', 'OUAOUIZERTH'), ('Ouarzazate', 'OUARZAZATE'), ('Ouazzane', 'OUAZZANE'), ('Oued-zem', 'OUED\xa0ZEM'), ('Oujda', 'OUJDA'), ('Oulad-mrah', 'OULAD\xa0MRAH'), ('Ouled-teima', 'OULED\xa0TEIMA'), ('Rabat', 'RABAT'), ('Safi', 'SAFI'), ('Sale', 'SALE'), ('Sefrou', 'SEFROU'), ('Settat', 'SETTAT'), ('Sidinifni', 'SIDI\xa0IFNI'), ('Sidi-kacem', 'SIDI\xa0KACEM'), ('Sidi-slimane', 'SIDI\xa0SLIMANE'), ('Skhirat', 'SKHIRAT'), ('Souk-larbaa', 'SOUK\xa0LARBAA'), ('Souk-sebt', 'SOUK\xa0SEBT'), ('Tahannaout', 'TAHANNAOUT'), ('Tamensourt', 'TAMENSOURT'), ('Tanger', 'TANGER'), ('Tantan', 'TANTAN'), ('Taounate', 'TAOUNATE'), ('Taourirt', 'TAOURIRT'), ('Targuist', 'TARGUIST'), ('Taroudant', 'TAROUDANT'), ('Tassila', 'TASSILA'), ('Tata', 'TATA'), ('Taza', 'TAZA'), ('Temara', 'TEMARA'), ('Tetouan', 'TETOUAN'), ('Tiflet', 'TIFLET'), ('Tinghir', 'TINGHIR'), ('Tit-mellil', 'TIT\xa0MELLIL'), ('Tiznit', 'TIZNIT'), ('Youssoufia', 'YOUSSOUFIA'), ('Zagora', 'ZAGORA'), ('Zaio', 'ZAIO')], default='Casablanca', max_length=150, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
                ('gsm', models.CharField(blank=True, max_length=255, null=True)),
                ('presentation', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('competence', models.TextField(blank=True, null=True)),
                ('rib', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('web', models.CharField(blank=True, max_length=255, null=True)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avocat',
                'verbose_name_plural': 'Avocats',
                'db_table': 'avocat',
                'managed': True,
            },
        ),
    ]
