# Generated by Django 2.2.24 on 2021-09-22 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avocat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, null=True)),
                ('immeuble', models.CharField(blank=True, max_length=255, null=True)),
                ('quartier', models.CharField(blank=True, max_length=255, null=True)),
                ('indication', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, choices=[(1, 'AGADIR'), (2, 'AHFIR'), (3, 'AIN\xa0AOUDA'), (4, 'AL\xa0AAROUI'), (5, 'AL\xa0HOCEIMA'), (6, 'ASILAH'), (7, 'ASSA'), (8, 'AZILAL'), (9, 'AZROU'), (10, 'BEN\xa0AHMED'), (11, 'BEN\xa0SLIMANE'), (12, 'BENGRIR'), (13, 'BENI\xa0MELLAL'), (14, 'BERKANE'), (15, 'BERRECHID'), (16, 'BIOUGRA'), (17, 'BOUARFA'), (18, 'BOUIZAKAREN'), (19, 'BOUJAAD'), (20, 'BOUJDOUR'), (21, 'BOUJNIBA'), (22, 'BOUZNIKA'), (23, 'CASABLANCA'), (24, 'CHEFCHAOUEN'), (25, 'CHICHAOUA'), (26, 'DAKHLA'), (27, 'DEMNATE'), (28, 'EL\xa0AIOUN'), (29, 'EL\xa0BROUJ'), (30, 'EL\xa0GARA'), (31, 'EL\xa0HAJEB'), (32, 'EL\xa0HAOUZ'), (33, 'EL\xa0JADIDA'), (34, 'EL\xa0KARIA'), (35, 'ERFOUD'), (36, 'ERRACHIDIA'), (37, 'ES-SEMARA'), (38, 'ESSAOUIRA'), (39, 'FES'), (40, 'FIGUIG'), (41, 'FNIDEQ'), (42, 'FQUIH\xa0BEN\xa0SALAH'), (43, 'GOULMIMA'), (44, 'GUELMIM'), (45, 'GUERCIF'), (46, 'HAD\xa0SOUALEM'), (47, 'HATTANE'), (48, 'IFRANE'), (49, 'IMZOUREN'), (50, 'INEZGANE'), (51, 'JERRADA'), (52, 'KALAA\xa0DES\xa0SRAGHNAS'), (53, 'KENITRA'), (54, 'KHENIFRA'), (55, 'KHMISSET'), (56, 'KHOURIBGA'), (57, 'KSAR\xa0EL\xa0KEBIR'), (58, 'KSAR\xa0SGHIR'), (59, 'KSBAT\xa0TADLA'), (60, 'LAAYOUNE'), (61, 'LAHRAOUYINE'), (62, 'LARACHE'), (63, 'MDIAQ'), (64, 'MACHRAA\xa0BELKSIRI'), (65, 'MARRAKECH'), (66, 'MARTIL'), (67, 'MEDIOUNA'), (68, 'MEKNES'), (69, 'MIDELT'), (70, 'MIRLEFT'), (71, 'MISSOUR'), (72, 'MOHAMMEDIA'), (73, 'MRIRT'), (74, 'NADOR'), (75, 'OUAOUIZERTH'), (76, 'OUARZAZATE'), (77, 'OUAZZANE'), (78, 'OUED\xa0ZEM'), (79, 'OUJDA'), (80, 'OULAD\xa0MRAH'), (81, 'OULED\xa0TEIMA'), (82, 'RABAT'), (83, 'SAFI'), (84, 'SALE'), (85, 'SEFROU'), (86, 'SETTAT'), (87, 'SIDI\xa0IFNI'), (88, 'SIDI\xa0KACEM'), (89, 'SIDI\xa0SLIMANE'), (90, 'SKHIRAT'), (91, 'SOUK\xa0LARBAA'), (92, 'SOUK\xa0SEBT'), (93, 'TAHANNAOUT'), (94, 'TAMENSOURT'), (95, 'TANGER'), (96, 'TANTAN'), (97, 'TAOUNATE'), (98, 'TAOURIRT'), (99, 'TARGUIST'), (100, 'TAROUDANT'), (101, 'TASSILA'), (102, 'TATA'), (103, 'TAZA'), (104, 'TEMARA'), (105, 'TETOUAN'), (106, 'TIFLET'), (107, 'TINGHIR'), (108, 'TIT\xa0MELLIL'), (109, 'TIZNIT'), (110, 'YOUSSOUFIA'), (111, 'ZAGORA'), (112, 'ZAIO')], max_length=150, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
                ('gsm', models.CharField(blank=True, max_length=255, null=True)),
                ('presentation', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('competence', models.TextField(blank=True, null=True)),
                ('rib', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('web', models.CharField(blank=True, max_length=255, null=True)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avocat',
                'verbose_name_plural': 'Avocats',
                'db_table': 'avocat',
            },
        ),
    ]
