# Generated by Django 2.2.24 on 2021-10-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='avocatcharge',
            table='avocat_charge',
        ),
    ]
