# Generated by Django 2.2.24 on 2021-10-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affaires', '0004_auto_20211007_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avocatcharge',
            options={'managed': True, 'ordering': ('-id',), 'verbose_name': 'AvocatCharge', 'verbose_name_plural': 'AvocatCharges'},
        ),
    ]
