from django.utils.translation import gettext_lazy as _

TYPE_PERSON = [
    (1, _('Particulier')), 
    (2, _('Entreprise'))
]

STATUS_JURIDIQUE = [
    (1001, _("L'entreprise individuelle")),
    (1002, _("La société à Responsabilité Limitée (S.A.R.L)")),
    (1003, _("La société en Nom Collectif")),
    (1004, _("La société en commandite simple")),
    (1005, _("La société anonyme simplifiée")),
    (1006, _("La société en commandite par actions")),
    (1007, _("La société anonyme")),
    (1008, _("La société en particulation")),
    (1009, _("Le groupement d'interêt économique")),
    (1010, _("Succursale")),
]

CORRESPONDENCE = [
    ('oui', _('Oui')),
    ('non', _('Non')),
    ('apres', _('Aprés validation')),
]

TYPE_AFFAIRES = [
    ('civil', _('Civil')),
    ('correctionnel', _('Correctionnel')),
    ('commercial', _('Commercial')),
    ('maritime', _('Maritime')),
    ('administratif', _('Administratif')),
    ('social', _('social')),
    ('famille', _('Famille')),
    ('conseil_juridique', _('Conseil Juridique')),
]

COMPLEMENTAIRES = [
    ('standard', _('Standard')),
    ('correctionnel', _('Correctionnel')),
    ('commercial', _('Commercial')),
    ('maritime', _('Maritime')),
    ('expropriation', _('Expropriation')),
    ('arbitage', _('Arbitage')),
    ('conseil_juridique', _('Conseil Juridique')),
    ('accident_travail', _('Accident de travail')),
    ('accident_circulation', _('Accident de circulation')),
]

PAGES = {
    1: _('accueil'),
    2: _('clients'),
    3: _('adversaires'),
    4: _('avocats adversaires'),
    5: _('affaires'),
    6: _('avocats charges'),
    7: _('departements'),
}

GENDERS = [
    ('M', _('Masculin')),
    ('F', _('Féminin'))
]

VILLES = [
    ('all', _('Toutes')),
    ('Agadir', _('AGADIR')),
    ('Ahfir', _('AHFIR')),
    ('Ain-aouda', _('AIN AOUDA')),
    ('Al-aaroui', _('AL AAROUI')),
    ('Al-hoceima', _('AL HOCEIMA')),
    ('Asilah', _('ASILAH')),
    ('Assa', _('ASSA')),
    ('Azilal', _('AZILAL')),
    ('Azrou', _('AZROU')),
    ('Ben-ahmed', _('BEN AHMED')),
    ('Ben-slimane', _('BEN SLIMANE')),
    ('Bengrir', _('BENGRIR')),
    ('Beni-mellal', _('BENI MELLAL')),
    ('Berkane', _('BERKANE')),
    ('Berrechid', _('BERRECHID')),
    ('Biougra', _('BIOUGRA')),
    ('Bouarfa', _('BOUARFA')),
    ('Bouizakaren', _('BOUIZAKAREN')),
    ('Boujaad', _('BOUJAAD')),
    ('Boujdour', _('BOUJDOUR')),
    ('Boujniba', _('BOUJNIBA')),
    ('Bouznika', _('BOUZNIKA')),
    ('Casablanca', _('CASABLANCA')),
    ('Chefchaouen', _('CHEFCHAOUEN')),
    ('Chichaoua', _('CHICHAOUA')),
    ('Dakhla', _('DAKHLA')),
    ('Demnate', _('DEMNATE')),
    ('El-aioun', _('EL AIOUN')),
    ('El-brouj', _('EL BROUJ')),
    ('El-gara', _('EL GARA')),
    ('El-hajeb', _('EL HAJEB')),
    ('El-haouz', _('EL HAOUZ')),
    ('El-jadida', _('EL JADIDA')),
    ('El-karia', _('EL KARIA')),
    ('Erfoud', _('ERFOUD')),
    ('Errachidia', _('ERRACHIDIA')),
    ('Es-semara', _('ES-SEMARA')),
    ('Essaouira', _('ESSAOUIRA')),
    ('Fes', _('FES')),
    ('Figuig', _('FIGUIG')),
    ('Fnideq', _('FNIDEQ')),
    ('Fquih-ben-salah', _('FQUIH BEN SALAH')),
    ('Goulmima', _('GOULMIMA')),
    ('Guelmim', _('GUELMIM')),
    ('Guercif', _('GUERCIF')),
    ('Had-soualem', _('HAD SOUALEM')),
    ('Hattane', _('HATTANE')),
    ('Ifrane', _('IFRANE')),
    ('Imzouren', _('IMZOUREN')),
    ('Inezgane', _('INEZGANE')),
    ('Jerrada', _('JERRADA')),
    ('Kalaa-des-sraghnas', _('KALAA DES SRAGHNAS')),
    ('Kenitra', _('KENITRA')),
    ('Khenifra', _('KHENIFRA')),
    ('Khmisset', _('KHMISSET')),
    ('Khouribga', _('KHOURIBGA')),
    ('Ksar-el-kebir', _('KSAR EL KEBIR')),
    ('Ksar-sghir', _('KSAR SGHIR')),
    ('Ksbat-tadla', _('KSBAT TADLA')),
    ('Laayoune', _('LAAYOUNE')),
    ('Lahraouyine', _('LAHRAOUYINE')),
    ('Larache', _('LARACHE')),
    ('Mdiaq', _('MDIAQ')),
    ('Machraa-belksiri', _('MACHRAA BELKSIRI')),
    ('Marrakech', _('MARRAKECH')),
    ('Martil', _('MARTIL')),
    ('Mediouna', _('MEDIOUNA')),
    ('Meknes', _('MEKNES')),
    ('Midelt', _('MIDELT')),
    ('Mirleft', _('MIRLEFT')),
    ('Missour', _('MISSOUR')),
    ('Mohammedia', _('MOHAMMEDIA')),
    ('Mrirt', _('MRIRT')),
    ('Nador', _('NADOR')),
    ('Ouaouizerth', _('OUAOUIZERTH')),
    ('Ouarzazate', _('OUARZAZATE')),
    ('Ouazzane', _('OUAZZANE')),
    ('Oued-zem', _('OUED ZEM')),
    ('Oujda', _('OUJDA')),
    ('Oulad-mrah', _('OULAD MRAH')),
    ('Ouled-teima', _('OULED TEIMA')),
    ('Rabat', _('RABAT')),
    ('Safi', _('SAFI')),
    ('Sale', _('SALE')),
    ('Sefrou', _('SEFROU')),
    ('Settat', _('SETTAT')),
    ('Sidinifni', _('SIDI IFNI')),
    ('Sidi-kacem', _('SIDI KACEM')),
    ('Sidi-slimane', _('SIDI SLIMANE')),
    ('Skhirat', _('SKHIRAT')),
    ('Souk-larbaa', _('SOUK LARBAA')),
    ('Souk-sebt', _('SOUK SEBT')),
    ('Tahannaout', _('TAHANNAOUT')),
    ('Tamensourt', _('TAMENSOURT')),
    ('Tanger', _('TANGER')),
    ('Tantan', _('TANTAN')),
    ('Taounate', _('TAOUNATE')),
    ('Taourirt', _('TAOURIRT')),
    ('Targuist', _('TARGUIST')),
    ('Taroudant', _('TAROUDANT')),
    ('Tassila', _('TASSILA')),
    ('Tata', _('TATA')),
    ('Taza', _('TAZA')),
    ('Temara', _('TEMARA')),
    ('Tetouan', _('TETOUAN')),
    ('Tiflet', _('TIFLET')),
    ('Tinghir', _('TINGHIR')),
    ('Tit-mellil', _('TIT MELLIL')),
    ('Tiznit', _('TIZNIT')),
    ('Youssoufia', _('YOUSSOUFIA')),
    ('Zagora', _('ZAGORA')),
    ('Zaio', _('ZAIO')),
]
