from django.utils.translation import gettext_lazy as _

TYPE_CLIENT = [
    (1, _('Particulier')), 
    (2, _('Entreprise'))
]

STATUS_JURIDIQUE = [
    (1001, _("L'entreprise individuelle")),
    (1002, _("La société à Responsabilité Limitée (S.A.R.L)")),
    (1003, _("La société en Nom Collectif")),
    (1004, _("La société en commandite simple")),
    (1005, _("La société anonyme simplifiée")),
    (1006, _("La société en commandite par actions")),
    (1007, _("La société anonyme")),
    (1008, _("La société en particulation")),
    (1009, _("Le groupement d'interêt économique")),
    (1010, _("Succursale")),
]

GENDERS = [
    ('M', _('Masculin')),
    ('F', _('Féminin'))
]

VILLES = [
    (1, _('AGADIR')),
    (2, _('AHFIR')),
    (3, _('AIN AOUDA')),
    (4, _('AL AAROUI')),
    (5, _('AL HOCEIMA')),
    (6, _('ASILAH')),
    (7, _('ASSA')),
    (8, _('AZILAL')),
    (9, _('AZROU')),
    (10, _('BEN AHMED')),
    (11, _('BEN SLIMANE')),
    (12, _('BENGRIR')),
    (13, _('BENI MELLAL')),
    (14, _('BERKANE')),
    (15, _('BERRECHID')),
    (16, _('BIOUGRA')),
    (17, _('BOUARFA')),
    (18, _('BOUIZAKAREN')),
    (19, _('BOUJAAD')),
    (20, _('BOUJDOUR')),
    (21, _('BOUJNIBA')),
    (22, _('BOUZNIKA')),
    (23, _('CASABLANCA')),
    (24, _('CHEFCHAOUEN')),
    (25, _('CHICHAOUA')),
    (26, _('DAKHLA')),
    (27, _('DEMNATE')),
    (28, _('EL AIOUN')),
    (29, _('EL BROUJ')),
    (30, _('EL GARA')),
    (31, _('EL HAJEB')),
    (32, _('EL HAOUZ')),
    (33, _('EL JADIDA')),
    (34, _('EL KARIA')),
    (35, _('ERFOUD')),
    (36, _('ERRACHIDIA')),
    (37, _('ES-SEMARA')),
    (38, _('ESSAOUIRA')),
    (39, _('FES')),
    (40, _('FIGUIG')),
    (41, _('FNIDEQ')),
    (42, _('FQUIH BEN SALAH')),
    (43, _('GOULMIMA')),
    (44, _('GUELMIM')),
    (45, _('GUERCIF')),
    (46, _('HAD SOUALEM')),
    (47, _('HATTANE')),
    (48, _('IFRANE')),
    (49, _('IMZOUREN')),
    (50, _('INEZGANE')),
    (51, _('JERRADA')),
    (52, _('KALAA DES SRAGHNAS')),
    (53, _('KENITRA')),
    (54, _('KHENIFRA')),
    (55, _('KHMISSET')),
    (56, _('KHOURIBGA')),
    (57, _('KSAR EL KEBIR')),
    (58, _('KSAR SGHIR')),
    (59, _('KSBAT TADLA')),
    (60, _('LAAYOUNE')),
    (61, _('LAHRAOUYINE')),
    (62, _('LARACHE')),
    (63, _('MDIAQ')),
    (64, _('MACHRAA BELKSIRI')),
    (65, _('MARRAKECH')),
    (66, _('MARTIL')),
    (67, _('MEDIOUNA')),
    (68, _('MEKNES')),
    (69, _('MIDELT')),
    (70, _('MIRLEFT')),
    (71, _('MISSOUR')),
    (72, _('MOHAMMEDIA')),
    (73, _('MRIRT')),
    (74, _('NADOR')),
    (75, _('OUAOUIZERTH')),
    (76, _('OUARZAZATE')),
    (77, _('OUAZZANE')),
    (78, _('OUED ZEM')),
    (79, _('OUJDA')),
    (80, _('OULAD MRAH')),
    (81, _('OULED TEIMA')),
    (82, _('RABAT')),
    (83, _('SAFI')),
    (84, _('SALE')),
    (85, _('SEFROU')),
    (86, _('SETTAT')),
    (87, _('SIDI IFNI')),
    (88, _('SIDI KACEM')),
    (89, _('SIDI SLIMANE')),
    (90, _('SKHIRAT')),
    (91, _('SOUK LARBAA')),
    (92, _('SOUK SEBT')),
    (93, _('TAHANNAOUT')),
    (94, _('TAMENSOURT')),
    (95, _('TANGER')),
    (96, _('TANTAN')),
    (97, _('TAOUNATE')),
    (98, _('TAOURIRT')),
    (99, _('TARGUIST')),
    (100, _('TAROUDANT')),
    (101, _('TASSILA')),
    (102, _('TATA')),
    (103, _('TAZA')),
    (104, _('TEMARA')),
    (105, _('TETOUAN')),
    (106, _('TIFLET')),
    (107, _('TINGHIR')),
    (108, _('TIT MELLIL')),
    (109, _('TIZNIT')),
    (110, _('YOUSSOUFIA')),
    (111, _('ZAGORA')),
    (112, _('ZAIO')),
]
